
handlers:
- url: '/'
  static_files: 'index.html'
  upload: '.*'

- url: '/404.html'
  static_files: '404.html'
  upload: '.*'


- url: '/feed/.*'
  static_files: 'atom.xml'
  upload: '.*'


- url: '/([^/]+)'
  static_files: '\1'
  upload: '.*'

- url: '/(.*?)/(.*?)/(.*?)/(.*?)/?'
  static_files: '/\1/\2/\3/\4/index.html'
  upload: '.*'

- url: '/(.*?)/(.*?)/(.*?)/'
  static_files: '\1/\2/\3/index.html'
  upload: '.*'


- url: '/(.*?)/(.*?)/'
  static_files: '\1/\2/index.html'
  upload: '.*'

- url: '/([^/]+)/'
  static_files: '\1/index.html'
  upload: '.*'


- url: '/(.*)/(.*)'
  static_files: '\1/\2'
  upload: '.*'
